# Copyright 2025 Canonical Ltd.
# See LICENSE file for licensing details.

name: RTD workflows

on:
  workflow_call:
    inputs:
      enable-sphinx-python-dependency-build-checks:
        description: Whether to enable the Sphinx and Python dependency build checks.
        type: boolean
        default: true
  pull_request:
    paths: 
      - 'docs/**'

jobs:
  automatic-doc-checks:
    name: Automatic doc checks
    uses: canonical/sphinx-docs-starter-pack/.github/workflows/automatic-doc-checks.yml@dev
  check-removed-urls:
    name: Check removed URLs
    uses: canonical/sphinx-docs-starter-pack/.github/workflows/check-removed-urls.yml@dev
  markdown-style-checks:
    name: Markdown style checks
    uses: canonical/sphinx-docs-starter-pack/.github/workflows/markdown-style-checks.yml@dev
  sphinx-python-dependency-build-checks:
    name: Sphinx and Python dependency build checks
    if: ${{ inputs.enable-sphinx-python-dependency-build-checks }}
    uses: canonical/sphinx-docs-starter-pack/.github/workflows/sphinx-python-dependency-build-checks.yml@dev

