name: Generate terraform docs
on:
  workflow_call:
    inputs:
      terraform-directory:
        type: string
        description: The working directory for the terraform
        default: "terraform"

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5.0.0
      with:
        ref: ${{ github.event.pull_request.head.ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@v1.4.1
      with:
        working-dir: ${{ inputs.terraform-directory }}
        output-file: README.md
        output-method: replace
    - uses: planetscale/ghcommit-action@v0.2.17
      with:
        commit_message: "terraform-docs: automated action"
        repo: ${{ github.event.pull_request.head.repo.full_name }}
        branch: ${{ github.event.pull_request.head.ref }}
        file_pattern: '${{ inputs.terraform-directory }}/*.md'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
